### ISSUE TITLE
[Bug]: 404 Not Found - nginx on wp/wp-admin

### ISSUE THREAD

**Issue by ghost** [agence-adeliom/docker-images#3]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Images

adeliom/php:7.4-nginx-node16

### Platform

macOS

### What happened?

Impossible to access admin on wordpress with nginx config.

### Steps to reproduce

1. https://adeliom-formation.lndo.site/wp/wp-admin

### Expected behavior

Access to admin 

### Screenshots or Videos

![Capture d’écran 2022-10-11 à 09 02 34](https://user-images.githubusercontent.com/105054171/195019442-986c24f5-0037-421f-8240-531f31f8e795.png)
<img width="1440" alt="Capture d’écran 2022-10-11 à 09 09 07" src="https://user-images.githubusercontent.com/105054171/195019826-bfab1663-e0cf-4273-a28d-819b6a037e5f.png">

**Comment by arnaud-ritti** [comment]
@SamyAdeliom It was the `internal` directive in the nginx default template who messed up. Rebuild is in progress
